/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gs_tdriver */

#ifndef _Included_com_gs_tdriver
#define _Included_com_gs_tdriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gs_tdriver
 * Method:    Call_julia
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gs_tdriver_Call_1julia
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
